## Introduction to tensors

In [ ]:
Tensor : generalization of vectors and matrices and is  understood as a multidimensional array
- A vector is a one-dimensional or first order tensor and a matrix is a two-dimensional or second order tensor

In [3]:
# importing libraries

import tensorflow as tf
import numpy as np

In [2]:
# Rank zero tensor
# rank is also known as "order", "degree", or "ndims"
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
# Rank 1 tensor

rank_1_tensor = tf.constant([2.0, 4.0,5.0])
print(rank_1_tensor)

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float32)


In [4]:
# set datatype at creation time

rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)

print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [5]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [6]:
# convert tensor to a numpy array

rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

# Basic mathematics on tensors


In [8]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n") # element wise addition
print(tf.multiply(a, b), "\n") # element wise multiplication
print(tf.matmul(a, b), "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [9]:
# various operations on tensor


c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.math.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [10]:
# broadcasting 

# smaller tensors are "stretched " automatically to fit larger tensors


x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [11]:
# reshape tensors

x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


In [12]:
# convert to a python list

reshaped = tf.reshape(x , [1,3])

In [13]:
print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


In [1]:
# Different types of tensors

In [5]:
## Ragged tensor


ragged_list = [
    [0,1,2,3],
    [4,5],
    [6,7,8],
    [9]]

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [7]:
# Tensors can be strings too. Here is a scalar string

scalar_string_tensor = tf.constant("gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'gray wolf', shape=(), dtype=string)
